import mongoose from "mongoose";
import { connectDB } from "../config/db";
import { auth } from "../lib/auth";
import { Trip } from "../models/Trip";

const DEMO = { name: "Demo User", email: "demo@tripplanner.com", password: "Demo1234!" };

const daysFromNow = (d: number) => new Date(Date.now() + d * 24 * 60 * 60 * 1000);
const img = (id: string) => `https://images.unsplash.com/${id}?w=800&q=80&auto=format&fit=crop`;

const trips = [
  { title: "Cox's Bazar Beach Escape", destination: "Cox's Bazar, Bangladesh", price: 12500, durationDays: 3, category: "beach", rating: 4.6, startDate: daysFromNow(14), imageUrl: img("photo-1590001155093-a3c66ab0c3ff"), shortDescription: "Three relaxed days on the world's longest natural sea beach with sunset views and fresh seafood.", fullDescription: "Wake up to the sound of the Bay of Bengal on the world's longest unbroken sea beach. This three-day escape covers Laboni Beach, Himchari waterfall, and Inani's coral-strewn shore. Evenings are for beachside seafood barbecues and the famous Cox's Bazar sunset. Comfortable AC hotel stay and all local transport included." },
  { title: "Sajek Valley Cloud Trek", destination: "Sajek, Rangamati, Bangladesh", price: 9800, durationDays: 2, category: "nature", rating: 4.7, startDate: daysFromNow(10), imageUrl: img("photo-1506905925346-21bda4d32df4"), shortDescription: "Sleep above the clouds in Sajek's hilltop cottages and catch a sunrise you'll never forget.", fullDescription: "Sajek sits on a ridge in the Kasalong range where clouds drift below your balcony at dawn. This two-day trip includes the jeep ride up the winding Baghaihat road, a sunrise viewpoint hike to Konglak Para, traditional bamboo chicken dinner, and a night in a hilltop eco-cottage. Perfect quick reset from city life." },
  { title: "Sundarbans Mangrove Safari", destination: "Sundarbans, Bangladesh", price: 18500, durationDays: 3, category: "adventure", rating: 4.8, startDate: daysFromNow(21), imageUrl: img("photo-1549366021-9f761d450615"), shortDescription: "Cruise the world's largest mangrove forest in search of the Royal Bengal Tiger.", fullDescription: "Board a liveaboard vessel from Khulna and drift through the tidal channels of the world's largest mangrove forest, a UNESCO World Heritage Site. Spot spotted deer, crocodiles, kingfishers, and — if luck favors you — the Royal Bengal Tiger. Includes all meals aboard, forest permits, armed forest guide, and small-boat excursions into narrow creeks at high tide." },
  { title: "Srimangal Tea Garden Retreat", destination: "Srimangal, Sylhet, Bangladesh", price: 8500, durationDays: 2, category: "nature", rating: 4.5, startDate: daysFromNow(7), imageUrl: img("photo-1563514227147-6d2ff665a6a0"), shortDescription: "Cycle through endless tea gardens, taste seven-layer tea, and walk Lawachara rainforest.", fullDescription: "Srimangal is Bangladesh's tea capital, and this weekend retreat puts you in the middle of its rolling green estates. Cycle the garden roads at golden hour, walk the trails of Lawachara National Park listening for hoolock gibbons, and sip the famous seven-layer tea where it was invented. Eco-resort stay with breakfast included." },
  { title: "Old Dhaka Heritage Walk", destination: "Dhaka, Bangladesh", price: 3500, durationDays: 1, category: "cultural", rating: 4.3, startDate: daysFromNow(5), imageUrl: img("photo-1583422409516-2895a77efded"), shortDescription: "A full-day guided walk through Lalbagh Fort, Ahsan Manzil, and the lanes of Puran Dhaka.", fullDescription: "Four hundred years of history packed into one day. Start at Lalbagh Fort's Mughal ramparts, continue to the pink palace of Ahsan Manzil, weave through Shankhari Bazar's craftsman lanes, and finish with biryani at a legendary Puran Dhaka kitchen. A local historian guides the walk; rickshaw hops and lunch included." },
  { title: "Bali Beach & Temple Week", destination: "Bali, Indonesia", price: 68000, durationDays: 6, category: "beach", rating: 4.8, startDate: daysFromNow(30), imageUrl: img("photo-1537996194471-e657df975ab4"), shortDescription: "Six days across Uluwatu cliffs, Ubud rice terraces, and Seminyak sunsets.", fullDescription: "Bali rewards every kind of traveler. This six-day loop starts on Seminyak's sands, climbs to the clifftop Uluwatu temple for the kecak fire dance at dusk, then heads inland to Ubud for the Tegallalang rice terraces, the Sacred Monkey Forest, and a Balinese cooking class. Includes 4-star stays, breakfasts, private driver, and airport transfers." },
  { title: "Bangkok City Break", destination: "Bangkok, Thailand", price: 42000, durationDays: 4, category: "city-break", rating: 4.5, startDate: daysFromNow(18), imageUrl: img("photo-1508009603885-50cf7c579365"), shortDescription: "Grand Palace mornings, floating market afternoons, and rooftop-bar nights in Bangkok.", fullDescription: "Four days in Southeast Asia's most electric city. Tour the Grand Palace and Wat Pho's reclining Buddha before the heat peaks, boat through Damnoen Saduak floating market, shop Chatuchak's 15,000 stalls, and end each night with street food in Chinatown or a rooftop view from Sathorn. Hotel, breakfasts, and guided day tours included." },
  { title: "Kathmandu & Nagarkot Himalayan View", destination: "Kathmandu, Nepal", price: 35000, durationDays: 4, category: "cultural", rating: 4.6, startDate: daysFromNow(25), imageUrl: img("photo-1544735716-392fe2489ffa"), shortDescription: "Durbar squares, Boudhanath's great stupa, and a Himalayan sunrise from Nagarkot.", fullDescription: "Kathmandu Valley holds seven UNESCO World Heritage Sites within a day's reach. Explore the medieval courtyards of Patan and Bhaktapur, spin prayer wheels at Boudhanath, and watch the evening aarti at Pashupatinath. The final night moves to a Nagarkot hilltop lodge for a sunrise panorama across the Himalayas — Everest visible on clear mornings." },
  { title: "Maldives Overwater Escape", destination: "Maldives", price: 145000, durationDays: 5, category: "beach", rating: 4.9, startDate: daysFromNow(40), imageUrl: img("photo-1514282401047-d79a71a590e8"), shortDescription: "Five days in an overwater villa with house-reef snorkeling and sandbank picnics.", fullDescription: "The definitive tropical reset. Stay in an overwater villa with steps straight into a turquoise lagoon, snorkel the house reef with mantas and turtles, take a sunset dolphin cruise, and dine on a private sandbank. Seaplane transfers, half-board dining, and one couples' spa session included. Honeymoon favorite." },
  { title: "Istanbul Two-Continent City Break", destination: "Istanbul, Türkiye", price: 78000, durationDays: 5, category: "city-break", rating: 4.7, startDate: daysFromNow(35), imageUrl: img("photo-1524231757912-21f4fe3a7200"), shortDescription: "Hagia Sophia, the Grand Bazaar, and a Bosphorus cruise between Europe and Asia.", fullDescription: "Only one city sits on two continents. Five days across Sultanahmet's imperial monuments — Hagia Sophia, the Blue Mosque, Topkapi Palace — plus the labyrinth of the Grand Bazaar, a hammam session, and a Bosphorus sunset cruise from Europe to Asia and back. Boutique hotel in the old city with Turkish breakfast daily." },
  { title: "Bandarban Hill Trekking Expedition", destination: "Bandarban, Bangladesh", price: 11500, durationDays: 4, category: "adventure", rating: 4.6, startDate: daysFromNow(16), imageUrl: img("photo-1551632811-561732d1e306"), shortDescription: "Four days trekking to Nilgiri, Boga Lake, and remote hill villages of Bandarban.", fullDescription: "Bangladesh's most dramatic landscapes are in Bandarban. This four-day expedition covers the cloud-level viewpoint at Nilgiri, the mysterious blue waters of Boga Lake, and Nafakhum waterfall, with nights in indigenous village homestays. A certified trekking guide leads throughout; moderate fitness required. All permits, meals, and 4x4 transfers arranged." },
  { title: "Tokyo Neon & Tradition", destination: "Tokyo, Japan", price: 135000, durationDays: 6, category: "city-break", rating: 4.8, startDate: daysFromNow(45), imageUrl: img("photo-1540959733332-eab4deabeeaf"), shortDescription: "Six days from Shibuya's neon to Asakusa's temples, with a Mount Fuji day trip.", fullDescription: "Tokyo compresses centuries into single street corners. Cross the Shibuya scramble, eat your way through Tsukiji's outer market, find quiet at Meiji Shrine and Senso-ji, and geek out in Akihabara. Day five heads to Hakone for open-air onsen bathing with Mount Fuji views. Includes hotel, 6-day metro pass, and Hakone day tour." },
  { title: "Kuakata Panoramic Sea Beach", destination: "Kuakata, Bangladesh", price: 7500, durationDays: 2, category: "beach", rating: 4.2, startDate: daysFromNow(9), imageUrl: img("photo-1507525428034-b723cf961d3e"), shortDescription: "The rare beach where you can watch both sunrise and sunset over the sea.", fullDescription: "Kuakata — the 'daughter of the sea' — is one of the few beaches on Earth offering both sunrise and sunset over open water. This easy two-day trip includes Gangamati mangrove forest, the century-old Buddhist temple with its bronze statue, Rakhine village handicraft stalls, and plenty of unhurried beach time. Hotel and meals included." },
  { title: "Cappadocia Balloon & Cave Towns", destination: "Cappadocia, Türkiye", price: 92000, durationDays: 4, category: "adventure", rating: 4.9, startDate: daysFromNow(50), imageUrl: img("photo-1641128324972-af3212f0f6bd"), shortDescription: "Sunrise hot-air ballooning over fairy chimneys and nights in a cave hotel.", fullDescription: "Few travel moments beat floating over Cappadocia's fairy chimneys at dawn among a hundred balloons. Between flights, explore the underground city of Derinkuyu, hike the Rose Valley at sunset, tour Göreme's rock-cut Byzantine churches, and sleep in an authentic cave hotel. Balloon flight, all entry fees, and daily breakfast included." },
  { title: "Sylhet Ratargul & Bisnakandi", destination: "Sylhet, Bangladesh", price: 9000, durationDays: 3, category: "nature", rating: 4.4, startDate: daysFromNow(12), imageUrl: img("photo-1439066615861-d1af74d74000"), shortDescription: "Paddle the Ratargul swamp forest and wade the crystal streams of Bisnakandi.", fullDescription: "Sylhet's water-carved landscapes are unlike anywhere else in the country. Glide by boat through the submerged trees of Ratargul — Bangladesh's only freshwater swamp forest — then travel to Bisnakandi where mountain streams tumble out of the Meghalaya hills over beds of smooth stone. Includes Jaflong stone country, tea garden stops, and all boat fees." },
  { title: "Siem Reap Angkor Explorer", destination: "Siem Reap, Cambodia", price: 52000, durationDays: 4, category: "cultural", rating: 4.7, startDate: daysFromNow(28), imageUrl: img("photo-1563492065599-3520f775eeed"), shortDescription: "Sunrise at Angkor Wat and three days among the temples of the Khmer Empire.", fullDescription: "Angkor Wat at sunrise is a bucket-list moment, and it's only the beginning. Over three temple days, explore the enigmatic faces of Bayon, the tree-strangled ruins of Ta Prohm, and the intricate carvings of Banteay Srei with an expert Khmer guide. Evenings bring Pub Street energy and a Tonlé Sap floating village excursion. Hotel, temple passes, and guide included." },
  { title: "Kashmir Valley Houseboat Holiday", destination: "Srinagar, Kashmir, India", price: 58000, durationDays: 5, category: "nature", rating: 4.6, startDate: daysFromNow(38), imageUrl: img("photo-1566837945700-30057527ade0"), shortDescription: "Dal Lake houseboat nights, Gulmarg meadows, and Mughal gardens in the Kashmir Valley.", fullDescription: "They call it paradise on earth for a reason. Stay aboard a carved cedar houseboat on Dal Lake, ride a shikara through floating gardens at dawn, take the Gulmarg gondola into alpine meadows, and walk the Mughal gardens of Nishat and Shalimar. Includes houseboat and hotel nights, all transfers, and daily breakfast and dinner." },
  { title: "Dubai Desert & Skyline", destination: "Dubai, UAE", price: 88000, durationDays: 4, category: "city-break", rating: 4.5, startDate: daysFromNow(33), imageUrl: img("photo-1512453979798-5ea266f8880c"), shortDescription: "Burj Khalifa views, desert dune safari, and a dhow cruise through Dubai Marina.", fullDescription: "Dubai does spectacle like nowhere else. Ascend the Burj Khalifa's 124th-floor observation deck, lose an afternoon in the Dubai Mall and the old-town gold souks, then swap skyscrapers for sand with a dune-bashing desert safari, camel ride, and BBQ under the stars. Final evening: a traditional dhow dinner cruise through the Marina. 4-star hotel and transfers included." },
] as const;

async function seed() {
  await connectDB();

  // 1. Demo user — created via Better Auth's own API so hashing/format are correct
  let userId: string;
  try {
    const result = await auth.api.signUpEmail({ body: DEMO });
    userId = result.user.id;
    console.log("✅ Demo user created:", DEMO.email);
  } catch {
    // Already exists → sign in to fetch the id
    const result = await auth.api.signInEmail({
      body: { email: DEMO.email, password: DEMO.password },
    });
    userId = result.user.id;
    console.log("ℹ️ Demo user already exists, reusing:", DEMO.email);
  }

  // 2. Trips — idempotent
  await Trip.deleteMany({});
  await Trip.insertMany(trips.map((t) => ({ ...t, createdBy: userId })));
  console.log(`✅ Seeded ${trips.length} trips owned by demo user`);

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});